# Rubocop plugins to include.
require: "rubocop-rspec"

AllCops:
  Exclude:
    - "build/*"

# Alignment of hash rockets, keys are right aligned.
Layout/AlignHash:
  EnforcedHashRocketStyle: "separator"

# Use double quotes in string literals.
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/StringLiteralsInInterpolation:
  EnforcedStyle: "double_quotes"

# Single line method definitions don't need an empty line between them.
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Use slashes on single-line regexes, and %r on multi-line regexes.
Style/RegexpLiteral:
  EnforcedStyle: mixed

# Define known annotations.
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - XXX

# Compact class/module declaration.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Increase allowed cyclomatic complexity.
Metrics/CyclomaticComplexity:
  Max: 8

# Increase allowed perceived complexity.
Metrics/PerceivedComplexity:
  Max: 9

# Allow `$cfg` used JUST by rake tasks.
Style/GlobalVars:
  AllowedVariables:
    - $cfg
