# Rubocop plugins to include.
require: "rubocop-rspec"

AllCops:
  Exclude:
    - "build/*"

# Use double quotes in string literals.
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/StringLiteralsInInterpolation:
  EnforcedStyle: "double_quotes"

# Single line method definitions don't need an empty line between them.
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Use slashes on single-line regexes, and %r on multi-line regexes.
Style/RegexpLiteral:
  EnforcedStyle: mixed

# Define known annotations.
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - XXX

# Allow UTF-8 comments.
Style/AsciiComments:
  Enabled: false

# Allow UTF-8 identifiers.
Style/AsciiIdentifiers:
  Enabled: false

# Compact class/module declaration.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Allow `$cfg` used JUST by rake tasks.
Style/GlobalVars:
  AllowedVariables:
    - $cfg

# Check for a newline after the assignment operator in multi-line assignments.
Layout/MultilineAssignmentLayout:
  Enabled: true

# Suggests the usage of an auto resource cleanup version of a method
# (if available).
Style/AutoResourceCleanup:
  Enabled: true

# Checks if configured preferred methods are used over non-preferred.
Style/StringMethods:
  Enabled: true

# Enforces the names of some block params.
Style/SingleLineBlockParams:
  Enabled: true
